### ISSUE TITLE
Is rebaler suitable for polishing pacbio genomes?

### ISSUE THREAD

**Issue by tseemann** [rrwick/Rebaler#3]
I want to polish pacbio only assemblies with the original pacbio data.
ie. similar to what quiver and arrow do

I heard some are using minimap2 + racon for this, which is what rebaler seems to be doing.

Is it suitable?

**Comment by rrwick** [comment]
__Short version:__
Rebaler would work, but just running minimap2+Racon would be simpler and probably just as good.

__Long version:__
Rebaler would work, but quiver/arrow will likely do a better job because they use the raw data to get a better consensus. If you don't have the raw data (i.e. only fasta/fastq reads), then Rebaler might be appropriate.

That being said, you could probably just do minimap2+racon and get a nice result. Rebaler's first steps (replacing the assembly with corresponding parts of reads) isn't really necessary if you're starting with a decent assembly. The reason Rebaler does this is because I wrote it for my [basecaller comparison](https://github.com/rrwick/Basecalling-comparison). I didn't want to simply polish a finished genome because I didn't want its existing bases to influence the consensus. So Rebaler first swaps out the sequence using reads, and then polishes.

Also, Rebaler does multiple rounds of Racon polishing because it has to polish up messy read sequences. If you're starting with an already-decent assembly, then one round of Racon is probably enough.

Ryan

**Comment by rrwick** [comment]
To be clear, here's what I think Rebaler _is_ good for:
> Reassembling/polishing an assembly with long reads, using a reference assembly to guide the large-scale structure, but where you don't want reference assembly's basecalls to influence the basecalls in your new assembly.

**Comment by tseemann** [comment]
I only have the `-pacbio-raw subreads.fastq.gz` data.  

I'll look into implementing the `minimap2 + racon` step myself.

Thanks!
